repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ['--ignore=E203,F401,W503', '--max-line-length=104']
        exclude: ^(tests/|.venv/|venv/|venv.back/|.venv.back/|devscripts/|setup.py)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
